'use client';
import {useState} from 'react';
import Link from 'next/link';
import {usePrototype} from '@/lib/prototype/store';
import {catalog,integer,lineTotals,money,scenarioNames,totals,uid,ORDER_PAGE_SIZE,pageCount} from '@/lib/prototype/model';
import type {PaymentEntry} from '@/lib/prototype/types';
import LineEditor from './LineEditor';
import PosFunctionPanel from './PosFunctionPanel';
const stageNames={idle:'點餐前',ordering:'點餐中',paying:'付款中',completed:'付款完成'};
export default function Control({compact=false}:{compact?:boolean}){
 const {state:s,dispatch,error}=usePrototype();
 const [tab,setTab]=useState('pos');
 const [selected,setSelected]=useState<string|null>(null);
 const [method,setMethod]=useState<PaymentEntry['method']>('現金');
 const [amount,setAmount]=useState('100');
 const [message,setMessage]=useState('');
 const t=totals(s.order); const totalPages=pageCount(s.order); const editable=s.stage==='ordering';
 const line=s.order.lines.find(l=>l.id===selected);
 async function upload(file:File|undefined){
 if(!file)return;
 if(!['image/png','image/jpeg','image/webp'].includes(file.type)){setMessage('請選擇 PNG、JPEG 或 WebP 圖片。');return;}
 if(file.size>1024*1024){setMessage('圖片請小於 1 MB，以保留本機儲存空間。');return;}
 const image=await new Promise<string>((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result));r.onerror=reject;r.readAsDataURL(file);});
 dispatch({type:'slides',slides:[...s.slides,{id:uid(),title:file.name,subtitle:'本機素材',seconds:5,image}]});setMessage('圖片已加入輪播。');
 }
 return <section className={'control '+(compact?'compact':'')}><header className="control-header"><div><span className="eyebrow">EVERYDAY TEA / RESEARCH PROTOTYPE</span><h1>顧客顯示器工作台</h1><p>從這裡操作，讓每一筆交易清楚可見。</p></div><div className="header-actions"><Link href={compact?'/control':'/preview'}>{compact?'獨立控制台':'並排預覽'} ↗</Link><a href="/display" target="_blank" rel="noreferrer">開啟顧客視窗 ↗</a></div></header>
 <div className="status-bar"><span><i/>目前階段 <strong>{stageNames[s.stage]}</strong></span><span>訂單 #{s.order.number}</span><button className="primary" onClick={()=>{dispatch({type:'new'});setSelected(null);}}>開始新訂單</button></div>
 <nav className="tabs" aria-label="工作台頁籤">{[['pos','POS 模擬操作'],['research','研究情境控制台']].map(([id,label])=><button key={id} aria-pressed={tab===id} onClick={()=>setTab(id)}>{label}</button>)}</nav>
 {error&&<p role="alert" className="notice">{error}</p>}{message&&<p role="status" className="notice">{message}<button onClick={()=>setMessage('')}>關閉</button></p>}
 {tab==='pos'?<div className="pos-layout"><section className="panel catalog-panel"><div className="section-title"><h2>商品目錄</h2><span>現泡茶飲與茶點</span></div><div className="catalog">{catalog.map((p,i)=><button key={p.name} disabled={!editable} onClick={()=>dispatch({type:'add',index:i,now:Date.now()})}><span className="product-icon" aria-hidden="true">{i>=6?'▤':'▱'}</span><strong>{p.name}</strong><span>{money(p.price)}<b>＋</b></span></button>)}</div>{!editable&&<p className="muted">開始新訂單後即可加入商品。</p>}
 <div className="settings-section"><h2>會員與發票</h2><label className="check-label"><input type="checkbox" disabled={!editable} checked={s.pinComplimentary} onChange={e=>dispatch({type:"pinGifts",value:e.target.checked})}/>b���</label><label className="check-label"><input type="checkbox" disabled={!editable} checked={!!s.order.member} onChange={e=>dispatch({type:'order',patch:{member:e.target.checked?{name:'林小姐（測試）',code:'M0001'}:undefined}})}/>使用測試會員</label>{s.order.member&&<p className="muted">{s.order.member.name} · {s.order.member.code}</p>}
 <label>發票識別<select disabled={!editable} value={s.order.invoice?.type??''} onChange={e=>dispatch({type:'order',patch:{invoice:e.target.value?{type:e.target.value as 'taxId'|'carrier',value:e.target.value==='taxId'?'12345675':'/AB12CD3'}:null}})}><option value="">不使用</option><option value="carrier">手機載具</option><option value="taxId">公司統編</option></select></label>{s.order.invoice&&<label>{s.order.invoice.type==='taxId'?'統編':'載具'}內容<input disabled={!editable} value={s.order.invoice.value} onChange={e=>dispatch({type:'order',patch:{invoice:{type:s.order.invoice!.type,value:e.target.value}}})}/></label>}
 <label>整單折扣（NT$）<input disabled={!editable} type="number" min="0" value={s.order.discount?.amount??0} onChange={e=>dispatch({type:'order',patch:{discount:{level:'order',label:'整單優惠',amount:integer(Number(e.target.value))}}})}/></label></div></section>
 <section className="panel current-order"><div className="section-title"><h2>目前訂單 <small>{t.quantity} 項</small></h2><div className="pos-page-controls"><button disabled={s.page<=1} onClick={()=>dispatch({type:'page',page:s.page-1})}>上一頁</button><span>第 {s.page}／{totalPages} 頁</span><button disabled={s.page>=totalPages} onClick={()=>dispatch({type:'page',page:s.page+1})}>下一頁</button><button disabled={!editable} onClick={()=>dispatch({type:'clear'})}>清空</button></div></div><div className="control-lines">{s.order.lines.length?s.order.lines.slice((s.page-1)*ORDER_PAGE_SIZE,s.page*ORDER_PAGE_SIZE).map(l=><div className={'control-line '+(selected===l.id?'selected':'')} key={l.id}><div className="control-line-title"><button onClick={()=>{setSelected(selected===l.id?null:l.id);dispatch({type:'focus',id:l.id,now:Date.now()});}}><b>{l.quantity} × {l.name}</b><small>{l.complimentary?'招待':l.specs.join(' / ')}</small></button><strong>{money(lineTotals(l).net)}</strong></div><div className="row-actions"><button onClick={()=>dispatch({type:'focus',id:l.id,now:Date.now()})}>帶看品項</button><button disabled={!editable} onClick={()=>setSelected(selected===l.id?null:l.id)}>{selected===l.id?'收起編輯':'編輯'}</button><button disabled={!editable} onClick={()=>dispatch({type:'delete',id:l.id})}>刪除</button></div>{line?.id===l.id&&editable&&<LineEditor line={line}/>}</div>):<div className="control-empty">尚未加入商品<p>開始新訂單，選一杯好茶。</p></div>}</div><div className="control-total"><span>總計 <small>折扣 −{money(t.discount)}</small></span><strong>{money(t.total)}</strong></div>

 {(s.stage==='ordering'||s.stage==='paying')&&<section className="payment-controls"><h2>收款</h2><div className="mini-metrics"><span>已付 {money(t.paid)}</span><span>未付 {money(t.unpaid)}</span><span>找零 {money(t.change)}</span></div>{s.order.payments.map(p=><div className="payment-entry" key={p.id}><span>{p.method} {money(p.amount)}</span><button onClick={()=>dispatch({type:'removePayment',id:p.id})}>取消此筆</button></div>)}<div className="field-grid"><label>付款方式<select value={method} onChange={e=>setMethod(e.target.value as PaymentEntry['method'])}>{['現金','信用卡','行動支付'].map(m=><option key={m}>{m}</option>)}</select></label><label>收款金額<input type="number" min="1" value={amount} onChange={e=>setAmount(e.target.value)}/></label></div><button className="wide" disabled={t.unpaid===0} onClick={()=>{const n=integer(Number(amount));if(n<=0||(method!=='現金'&&n>t.unpaid)){setMessage('請輸入正整數；非現金付款不可超過未付金額。');return;}if(s.stage==='ordering')dispatch({type:'pay'});dispatch({type:'payment',payment:{id:uid(),method,amount:n}});if(n>=t.unpaid)dispatch({type:'complete',now:Date.now()});}}>加入付款</button><div className="row-actions"><button onClick={()=>dispatch({type:'resetPayments'})}>重設收款</button><button onClick={()=>dispatch({type:'cancelPay'})}>取消付款，回到點餐</button></div></section>}
 {s.stage==='completed'&&<p className="notice">付款完成。可立即開始新訂單，中斷返回首頁倒數。</p>}</section><PosFunctionPanel /></div>:
 <div className="research-layout"><section className="panel"><div className="section-title"><h2>研究情境</h2><span>一鍵載入，可繼續操作</span></div><div className="scenarios">{scenarioNames.map((name,index)=><button key={name} aria-pressed={s.scenario===index} onClick={()=>{dispatch({type:'scenario',index,now:Date.now()});setSelected(null);}}><span>{String(index+1).padStart(2,'0')}</span><strong>{name}</strong><span>↗</span></button>)}</div><p className="muted">情境 13 在付款完成後 2.5 秒自動開啟下一單，驗證倒數中斷。</p><div className="research-actions"><button disabled={s.stage!=='completed'} onClick={()=>dispatch({type:'pause',now:Date.now()})}>{s.paused?'繼續倒數':'暫停倒數'}</button><button onClick={()=>dispatch({type:'idle'})}>立即返回行銷頁</button><button onClick={()=>dispatch({type:'reset'})}>重設全部狀態</button></div></section>
 <section className="panel"><div className="section-title"><h2>行銷素材</h2><span>{s.slides.length} 張</span></div><p className="muted">點餐前全螢幕，點餐中左側輪播。</p><div className="slides-editor">{s.slides.map((slide,i)=><div className="slide-editor" key={slide.id}><div className="slide-thumbnail">{slide.image?<span style={{backgroundImage:'url("'+slide.image+'")'}}/>:<b>日常<br/>茶事</b>}</div><div><strong>{slide.title.replace('\n','')}</strong><label>輪播秒數<input aria-label={slide.title+'輪播秒數'} type="number" min="1" max="60" value={slide.seconds} onChange={e=>dispatch({type:'slides',slides:s.slides.map(v=>v.id===slide.id?{...v,seconds:Math.max(1,Math.min(60,integer(Number(e.target.value))))}:v)})}/></label><div className="row-actions"><button disabled={i===0} onClick={()=>{const a=[...s.slides];[a[i-1],a[i]]=[a[i],a[i-1]];dispatch({type:'slides',slides:a});}}>上移</button><button disabled={i===s.slides.length-1} onClick={()=>{const a=[...s.slides];[a[i+1],a[i]]=[a[i],a[i+1]];dispatch({type:'slides',slides:a});}}>下移</button><button disabled={s.slides.length===1} onClick={()=>dispatch({type:'slides',slides:s.slides.filter(v=>v.id!==slide.id)})}>移除</button></div></div></div>)}</div><label className="upload">＋ 上傳本機圖片<input type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>{void upload(e.target.files?.[0]).catch(()=>setMessage('圖片讀取失敗，請重試。'));e.target.value='';}}/></label><p className="muted">PNG、JPEG、WebP，每張最多 1 MB。上傳素材以灰階顯示。</p></section></div>}
 <footer className="control-footer"><span>日常茶事 · 顧客顯示器研究原型</span><span>本機同步 / 不蒐集受測者資料</span></footer></section>;
}
